"""user-users

Revision ID: 07c738ac5eaa
Revises: cc73a24c52c7
Create Date: 2022-08-17 11:19:02.762018

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "07c738ac5eaa"
down_revision = "cc73a24c52c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes", sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_foreign_key(None, "notes", "users", ["user_id"], ["uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_column("notes", "user_id")
    # ### end Alembic commands ###
