"""Note timestamps

Revision ID: 753c0972099e
Revises: 07c738ac5eaa
Create Date: 2022-08-20 04:08:31.133983

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "753c0972099e"
down_revision = "07c738ac5eaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notes",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
    )
    op.add_column(
        "notes",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_notes_created_at"), "notes", ["created_at"], unique=False)
    op.create_index(op.f("ix_notes_updated_at"), "notes", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_updated_at"), table_name="notes")
    op.drop_index(op.f("ix_notes_created_at"), table_name="notes")
    op.drop_column("notes", "updated_at")
    op.drop_column("notes", "created_at")
    # ### end Alembic commands ###
